export const INCREMENT = 'INCREMENT';
export const DECREASE = 'DECREASE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_GIT_USER = "FETCH_GIT_USER";
export const FETCH_GIT_USER_SUCCESS = 'FETCH_GIT_USER_SUCCESS';
export const FETCH_GIT_USER_FAILED = 'FETCH_GIT_USER_FAILED';

export const UPLOAD_GIT_USER = "UPLOAD_GIT_USER";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILED = "UPLOAD_FAILED";