name: comp version and create PR
on:
   workflow_dispatch:
   schedule:
   - cron:  '30 5,17 * * *'
      
jobs:
  updateVersion:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3       
      
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
      - id: ans
        run: |
          git branch
          echo ""
          export arg1=`cat package.json |  grep '"version":' | sed -E 's/.*"([^"]+)".*/\1/'`
          echo $arg1
          export arg2="`curl -H 'Authorization: token ${{ secrets.MY_ORG }}' --silent "https://api.github.com/repos/selftestdisco/searchgitusers/releases/latest" | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' `"
          echo $arg2
          python3 .github/cmpver.py  $arg1 $arg2  > ans.txt
          cat ans.txt
          echo "test=`python3 .github/cmpver.py $arg1 $arg2`"  >> $GITHUB_OUTPUT
        
      - run: echo ${{ steps.ans.outputs.test }}
    
      - if: ${{ steps.ans.outputs.test == 'Greater' }}
        name: create a branch
        run: |
          
          
          newversion=$(curl -H 'Authorization: token ${{ secrets.MY_ORG }}' --silent "https://api.github.com/repos/selftestdisco/searchgitusers/releases/latest" | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' )
          echo $newversion
          sed  -i -e "/version\":/s/[0-9]*\.[0-9]*\.[0-9]*/${newversion}/" package.json
          head -5 package.json
          
          git push origin :releaseVersionUpdate
          git checkout -b releaseVersionUpdate
          git branch
          git config user.name "random"
          git config user.email "random@example.com"
          git add package.json
          git commit -m "Version update"
          git push origin releaseVersionUpdate
          gh pr list
